---
name: ((DeploymentName))

releases:
- name: ((ReleaseName))
  version: '((ReleaseVersion))'

stemcells:
- alias: windows
  os: ((StemcellOs))
  version: '((StemcellVersion))'

update:
  canaries: 0
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

instance_groups:
- name: slow-compile
  instances: 1
  stemcell: windows
  azs: [((AZ))]
  vm_type: ((VmType))
  vm_extensions: [((VmExtensions))]
  networks:
  - name: ((Network))
  jobs:
  - name: slow-compile
    release: ((ReleaseName))
